### ISSUE TITLE
rst preview does not seem to work

### ISSUE THREAD

**Issue by mbibee** [zeis/kokoi#2]
Running MS windows.  Pandoc is installed and correctly converts .rst to html on the command prompt

if I make a markdown file, notes.md and just run

    kokoi

on the command line I see the message "Info  - Watching C:\Users....\docs\notes.md.  A browser window pops up that says "Kokoi, Greetings".  If I change the markdown files and save it then the browswer immediately updates and I see html rendering of the notes.md file. 

I have a rst than I can manually convert from rst to html on the command line using pandoc (looks good).
I invoke kokoi with 

    kokoi -e rst -c "pandoc -f rst -t html5" notes.rst

The browswer open with greetings from kokoi but I never see a Info notification that it is watching notes.rst.  Is my invocation incorrect.

BTW I changed all the utils.puts calls to console.log in the .js files.

**Comment by zeis** [comment]
Thank you very much for reporting this issue.

I've just updated the code. Please try it and let me know.

**Comment by mbibee** [comment]
rst preview is working now.  I can see rst getting rendered via pandoc in the command log and the resultant html shows up in a browser window.  Very responsive.  Nice!
