### ISSUE TITLE
handling of relative paths by kokoi when serving rendered html page

### ISSUE THREAD

**Issue by mbibee** [zeis/kokoi#3]
I am not sure if this is actually an issue with code of a mistake I am making.  I am writing restructured text and I have a situation that looks like this:

folderA\
     - file1.rst
     -my_imageA.png
folderB\
    -my_imageB.png

If my file1.rst constains

    .. image:: my_imageA.png
    .. image:: ../folderB/my_imageB.png

and kokoi is running on file1.rst with:

    kokoi -e rst -c "python C:\Anaconda2\Scripts\rst2html.py" file1.rst

The resultant html displayed in the web brower will display "my_imageA.png" as a picture.  However the second image will just display the relative path name ../folderB/my_imageB.png".  The html seems to be valid.  If I save this file and view it as a html page in a standalone browser I see both images.

It seems the issue is rather the node/kokoi server doesn't know where to find the directory ../folderB.  I tried starting kokoi a level above this but no good.  When kokoi is operating on "file1.rst" is it only able to serve images on the same filepath as "file1.rst"?

I would like to know if there is a way to set the server root at a level higher than "file1.rst".

Thanks!

**Comment by zeis** [comment]
Files (the dependencies) must be in the same directory of the parsed file or in a subdirectory. I've just tried moving one level up (and updating the paths accordingly) and it worked with a Markdown file showing both images. However it didn't work with an rst file. So I would say that it depends on the specific parser and the way it deals with paths (I'm not familiar with rst files), it does not seem an issue with kokoi to me.
